package io.github.eath1283.worldgend

// Real integration of the Stage 1 DFC compiler (Dfc.kt, findings #57/#58) into live
// generation. #59's first attempt cached compiled entries in a ConcurrentHashMap keyed
// by an allocated IdentityKey wrapper — measured as a real ~23-27% champion-scale
// REGRESSION despite a 99.95% cache hit rate, because the lookup itself (allocation +
// hashmap probe) cost more than a real Ap2 node's tiny original compute() body ever did.
// This version drops the side-table: OrionPatchAgent adds two real instance fields
// directly to Ap2 (orionDfcCompiled/orionDfcLeaves), so a cache hit is a plain field
// read, no allocation, no hashmap — compileFor() only runs the slow path once per
// instance (benignly re-run at most a few times under a first-access race across
// worker threads; the fields aren't volatile on purpose, see patchAp2Compute).
object DfcRuntime {

    // Sentinel for "tried, not compilable" — reference-compared from the generated
    // field-check code, so it must be a real, stable object, not a Kotlin object
    // singleton accessed through a getter (@JvmField forces a true static field).
    @JvmField
    val FAILED_MARKER: Any = Any()

    private val logFile = java.io.File("/tmp/orion_dfc_debug.log").apply { writeText("") }
    private fun debugLog(msg: String) {
        synchronized(logFile) { logFile.appendText("$msg\n") }
    }

    private val compileCount = java.util.concurrent.atomic.AtomicLong(0)
    private val evalCount = java.util.concurrent.atomic.AtomicLong(0)

    fun report(): String = "compiles=${compileCount.get()} evals=${evalCount.get()}"

    @JvmStatic
    fun countEval() {
        evalCount.incrementAndGet()
    }

    // Returns [DfcCompiled, Array<Any>] on success, null if `node` isn't compilable
    // (caller stores FAILED_MARKER itself — this function doesn't touch node's fields,
    // keeping all field access in one place, in the generated bytecode).
    @JvmStatic
    fun compileFor(node: Any): Array<Any>? {
        return try {
            val mc = Mc(node.javaClass.classLoader)
            val converter = DfcConverter(mc)
            val ast = converter.toAst(node)
            // A single Leaf pointing at the root itself (e.g. an Ap2 MIN/MAX node,
            // which toAst doesn't recognize as ADD/MUL) would call this same
            // compute() again at eval time — infinite recursion, not a fallback.
            if (ast is DfcNode.Leaf && converter.leaves.size == 1 && converter.leaves[0] === node) {
                return null
            }
            val compiled = DfcCompilerGen.compileInterpreted(node.javaClass.classLoader, ast)
            compileCount.incrementAndGet()
            arrayOf(compiled, converter.leaves.toTypedArray())
        } catch (t: Throwable) {
            debugLog("compileFor FAILED for ${node.javaClass.name}: $t")
            null
        }
    }
}
